'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {createClient} from '@/lib/supabase/client'
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)
export default function Products(){const s=createClient();const [items,setItems]=useState<any[]>([]);const [cats,setCats]=useState<any[]>([]);const [form,setForm]=useState<any>({name:'',slug:'',description:'',selling_price:'',jastip_fee:'',cost_price:'0',stock:'',category_id:'',is_available:true,is_featured:false});const [edit,setEdit]=useState<string|null>(null);const [msg,setMsg]=useState('');
 async function load(){const [{data:p,error:pe},{data:c}]=await Promise.all([s.from('products').select('*').order('created_at',{ascending:false}),s.from('categories').select('id,name').order('sort_order')]);if(pe)setMsg(pe.message);setItems(p||[]);setCats(c||[])} useEffect(()=>{load()},[])
 function start(p:any){setEdit(p.id);setForm({...p,selling_price:String(p.selling_price),jastip_fee:String(p.jastip_fee),cost_price:String(p.cost_price),stock:p.stock==null?'':String(p.stock)})}
 async function save(e:React.FormEvent){e.preventDefault();setMsg('Menyimpan…');const payload={name:form.name,slug:form.slug||form.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),description:form.description||null,cost_price:Number(form.cost_price||0),selling_price:Number(form.selling_price),jastip_fee:Number(form.jastip_fee||0),stock:form.stock===''?null:Number(form.stock),category_id:form.category_id||null,is_available:!!form.is_available,is_featured:!!form.is_featured};const q=edit?s.from('products').update(payload).eq('id',edit):s.from('products').insert(payload);const {error}=await q;if(error)setMsg(error.message);else{setMsg('Tersimpan.');setEdit(null);setForm({name:'',slug:'',description:'',selling_price:'',jastip_fee:'',cost_price:'0',stock:'',category_id:'',is_available:true,is_featured:false});load()}}
 return <main className="container py-10"><div className="flex justify-between"><div><Link href="/admin" className="text-sm">← Dashboard</Link><h1 className="mt-2 text-3xl font-black">Produk</h1></div></div><div className="mt-6 grid gap-6 lg:grid-cols-[380px_1fr]"><form onSubmit={save} className="card space-y-3 p-5"><h2 className="font-black">{edit?'Edit Produk':'Tambah Produk'}</h2>{['name','slug','description','cost_price','selling_price','jastip_fee','stock'].map(k=><label key={k} className="block text-sm font-bold">{k}<input required={k==='name'||k==='selling_price'} type={['cost_price','selling_price','jastip_fee','stock'].includes(k)?'number':'text'} className="mt-1 w-full rounded-xl border p-2 font-normal" value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="block text-sm font-bold">Kategori<select className="mt-1 w-full rounded-xl border p-2 font-normal" value={form.category_id||''} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">Tanpa kategori</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="flex gap-2"><input type="checkbox" checked={form.is_available} onChange={e=>setForm({...form,is_available:e.target.checked})}/> Tersedia</label><label className="flex gap-2"><input type="checkbox" checked={form.is_featured} onChange={e=>setForm({...form,is_featured:e.target.checked})}/> Featured</label>{msg&&<p className="text-sm opacity-70">{msg}</p>}<button className="btn btn-primary w-full">{edit?'Simpan Perubahan':'Tambah Produk'}</button>{edit&&<button type="button" className="btn border w-full" onClick={()=>setEdit(null)}>Batal</button>}</form><div className="space-y-3">{items.map(p=><div key={p.id} className="card flex items-center justify-between gap-4 p-4"><div><b>{p.name}</b><p className="text-sm opacity-60">{money(Number(p.selling_price))} + {money(Number(p.jastip_fee))} · stok {p.stock??'∞'}</p></div><button className="btn border" onClick={()=>start(p)}>Edit</button></div>)}</div></div></main>}
