'use client';
import { useEffect,useMemo,useState } from 'react';
import Link from 'next/link';
const rupiah=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
type Product={id:string;name:string;selling_price:number;jastip_fee:number};
type CartItem={product_id:string;name:string;price:number;jastip_fee:number;quantity:number};
export default function Checkout(){
 const[items,setItems]=useState<CartItem[]>([]),[form,setForm]=useState({name:'',phone:'',address:'',city:'Jakarta',notes:''}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState<any>(null);
 useEffect(()=>{
  const raw=localStorage.getItem('nfe-cart');
  if(!raw)return;
  try{
   const cart:Record<string,number>=JSON.parse(raw);
   fetch('/api/products').then(r=>r.ok?r.json():Promise.reject(new Error('Gagal memuat menu'))).then((products:Product[])=>{
    const next=Object.entries(cart).map(([id,quantity])=>{const p=products.find(x=>x.id===id);if(!p)return null;return {product_id:p.id,name:p.name,price:Number(p.selling_price)||0,jastip_fee:Number(p.jastip_fee)||0,quantity:Number(quantity)||0};}).filter((x):x is CartItem=>!!x&&x.quantity>0);
    setItems(next);
   }).catch(e=>setError(e.message));
  }catch{setError('Keranjang tidak valid. Silakan kembali ke menu dan pilih produk lagi.');}
 },[]);
 const subtotal=useMemo(()=>items.reduce((s,x)=>s+x.price*x.quantity,0),[items]),jastip=useMemo(()=>items.reduce((s,x)=>s+x.jastip_fee*x.quantity,0),[items]),total=subtotal+jastip;
 const submit=async(e:any)=>{e.preventDefault();if(items.length===0){setError('Keranjang kosong atau produk tidak tersedia.');return}setBusy(true);setError('');try{const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/create-order`,{method:'POST',headers:{'Content-Type':'application/json','apikey':process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||''},body:JSON.stringify({customer_name:form.name,customer_phone:form.phone,recipient_name:form.name,recipient_phone:form.phone,delivery_address:form.address,delivery_city:form.city,delivery_notes:form.notes,items:items.map(x=>({product_id:x.product_id,quantity:x.quantity}))})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Gagal membuat pesanan');localStorage.removeItem('nfe-cart');setDone(d.order)}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 if(done)return <main className="container py-16"><div className="mx-auto max-w-xl card p-8 text-center"><div className="text-6xl">🎉</div><h1 className="mt-4 text-3xl font-black">Pesanan berhasil dibuat!</h1><p className="mt-2 opacity-70">Nomor pesanan kamu:</p><div className="my-4 rounded-2xl bg-[#fff1dc] p-4 text-2xl font-black">{done.order_number}</div><p className="mb-6">Total {rupiah(Number(done.total))}</p><div className="flex gap-3"><Link className="btn btn-primary flex-1" href={`/order/${done.order_number}`}>Lacak Pesanan</Link><Link className="btn border flex-1" href="/">Kembali</Link></div></div></main>;
 return <main className="container py-10"><h1 className="text-4xl font-black">Checkout</h1>{items.length===0?<div className="card mt-6 p-8 text-center">{error||'Memuat keranjang...'} <Link className="text-[#e97827] font-bold" href="/menu">Kembali ke menu</Link></div>:<div className="mt-8 grid gap-8 lg:grid-cols-[1fr_380px]"><form onSubmit={submit} className="card space-y-5 p-6"><h2 className="text-2xl font-black">Data Pengiriman</h2>{[['name','Nama','text'],['phone','No. WhatsApp','tel'],['city','Kota','text']].map(([k,l,t])=><label key={k} className="block text-sm font-bold">{l}<input required className="mt-2 w-full rounded-xl border p-3 font-normal" type={t} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="block text-sm font-bold">Alamat lengkap<textarea required rows={4} className="mt-2 w-full rounded-xl border p-3 font-normal" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="block text-sm font-bold">Catatan<textarea rows={3} className="mt-2 w-full rounded-xl border p-3 font-normal" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>{error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button disabled={busy} className="btn btn-primary w-full disabled:opacity-50">{busy?'Memproses...':'Buat Pesanan'}</button></form><aside className="card h-fit p-6"><h2 className="text-xl font-black">Ringkasan</h2>{items.map(x=><div key={x.product_id} className="flex justify-between border-b py-3 text-sm"><span>{x.name} × {x.quantity}</span><b>{rupiah((x.price+x.jastip_fee)*x.quantity)}</b></div>)}<div className="mt-4 flex justify-between"><span>Subtotal</span><span>{rupiah(subtotal)}</span></div><div className="mt-2 flex justify-between"><span>Biaya jastip</span><span>{rupiah(jastip)}</span></div><div className="mt-4 flex justify-between text-xl font-black"><span>Total</span><span className="text-[#e97827]">{rupiah(total)}</span></div><p className="mt-4 text-xs opacity-60">Harga dan biaya jastip dihitung ulang oleh server saat order dibuat.</p></aside></div>}</main>}
